### ISSUE TITLE
[REFACTOR]NullPointerException при отключении последнего клиента

### ISSUE THREAD

**Issue by das13** [elenadonts/goGame#15]
Server\ClientHandler строка 100-101
**Server.writers.remove(writer);
Server.userOnline.remove(currentPlayer.getUserName());**
Это потенциальный NullPointerException (если подключен только один клиент и он отключается): нужно проверять writer и currentPlayer на null.

**Comment by das13** [comment]
Возникает при "неожиданном" выходе пользователя, т.е. если клиент завершил работу аварийно.

**Comment by elenadonts** [comment]
fixed in commit #62
