### ISSUE TITLE
[REFACTOR]Перенести в константы повторяющиеся строки

### ISSUE THREAD

**Issue by das13** [elenadonts/goGame#17]
В коде, связанном с работой с XML (PlayerWindowController, XMLGenerator) встречается много повторяющихся строк. Необходимо эти строки вынести в константы (можно в отдельный класс констант).

**Comment by das13** [comment]
Не все повторяющиеся строки вынесены в константы

**Comment by SergeySavchenko** [comment]
В интерфейсе ServerConstants добавил константы EMPTY_STRING = "" и ZERO_NUMBER = "0"
В интерфейсе ClientConstants добавил константы EMPTY_STRING = "" и TWO_NUMBER = "2"
Больше ничего не нашел. В коде есть еще два раза повторяющиеся части предложения, вроде  "Win: " или " with " или " points", но добавлять их в константы, как мне кажется, не совсем правильно
