### ISSUE TITLE
[SERVER]Более информативные сообщения в лог

### ISSUE THREAD

**Issue by das13** [elenadonts/goGame#4]
На сервере выводить в лог более информативные сообщения вместо **LOGGER.error(e)**

**Comment by elenadonts** [comment]
если это, например, исключение, где файл был не найден, при Logger.error(e) запишется его название(по которому будет понятно в чем дело) + стек трейс, будет достаточно информативно, не могу придумать, что еще записать,?

**Comment by das13** [comment]
Ну, например, полное имя файла
От выражения **Logger.error(e)** толку мало

**Comment by das13** [comment]
Обратите внимание на то, что в логировании ошибок **обязательно** д.б. стектрейс, т.е. вот такого
**LOGGER.error("Exception stopping server");**
не достаточно.

**Comment by elenadonts** [comment]
![image](https://user-images.githubusercontent.com/32674765/37462590-352e77b2-285b-11e8-95dd-bc16b9c5dd8d.png)

**Comment by elenadonts** [comment]
![image](https://user-images.githubusercontent.com/32674765/37462609-3eda1f00-285b-11e8-84a8-a3290dc1bf46.png)
В случае с не найденным файлом - его имя также логируется, и в других случаях стек-трейс дает достаточно информации, не совсем понятно, что еще дописывать

**Comment by das13** [comment]
На сервере достаточно стектрейса.
Можно указать путь, где этот файл искало приложение

**Comment by elenadonts** [comment]
тот файл он искал в корне, поэтому путь такой
![image](https://user-images.githubusercontent.com/32674765/37463986-9f246c68-285f-11e8-8f23-6ab8bfd4bdc4.png)
вот здесь виден путь к нему, тогда, если стек-трейсов достаточно, этот issue можно закрыть?

**Comment by das13** [comment]
Да, если путь виден в стектрейсе, то закрывай.
