### ISSUE TITLE
[CLIENT]Кнопка "Ban"

### ISSUE THREAD

**Issue by das13** [elenadonts/goGame#7]
делать неактивной кнопку "Ban", если в списке нет пользователей

**Comment by lobineugen** [comment]
Список пользователей не может быть пустым, так как если хоть один пользователь подключается то он будет виден в списке пользователей, и даже если это админ - сам себе он забанить не может.

**Comment by das13** [comment]
Согласен.
Хотя можно делать кнопку неактивной, когда пользователь выбирает в списке себя и/или в списке он один.
Закрываю
