### ISSUE TITLE
[ADD]Функционал остановки/перезапуска сервера

### ISSUE THREAD

**Issue by das13** [elenadonts/goGame#9]
Добавить функционал остановки/перезапуска сервера

**Comment by elenadonts** [comment]
fixed in commit #60

**Comment by das13** [comment]
Реализовано правильно, но есть один нюанс.
В Linux-подобных системах (да и в Windows тоже есть такая возможность) такие приложения запускаются, как правило, без привязки к консоли (точнее отвязанными от консоли). Как результат - ввести команду невозможно, т.к. попросту некуда.

Для решения задачи предлагаю (в дополнение к существующему методу) запускать приложение сервера с параметром в виде команды (stop, restart). Например так:
**java -jar server.jar -restart**
или наподобие. Подразумевается, что основной инстанс сервера запущен на этой же машине.
В самом приложении сервера нужно отследить наличие параметра и, если он есть, то послать команду основному инстансу через сокет и завершить работу (при наличии соединения, разумеется); если сервер запущен без параметров, то это обычный запуск и все работает в штатном режиме.
Ну а основной инстанс должен выполнить команду.
@elenadonts, переоткрой тикет, плиз.

**Comment by elenadonts** [comment]
поняла, исправим
